cmake_minimum_required(VERSION 3.7.0)
include(policyRules)
set(CMAKE_AUTOMOC ON)
add_definitions(-DQT_PLUGIN)
if( UNIX AND NOT (APPLE OR CYGWIN) )
	set(LINUX ON)
endif()
if(LINUX)
	set(PLUGINS_INSTALL_PATH "${LIB_INSTALL_DIR}/qomp/plugins")
elseif(WIN32)
	set(PLUGINS_INSTALL_PATH "${CMAKE_INSTALL_PREFIX}/plugins")
endif()
